stx: use reference instead of using exception by value.
This changeset fixes the following error message from gcc 9.2.0:
| [147/332] Compiling ../src/stx/common/trex_rx_port_mngr.cpp
| ../../src/stx/common/trex_stack_linux_based.cpp: In constructor 'CLinuxIfNode::CLinuxIfNode(const string&, const string&, const string&, const string&, CMcastFilter&)':
| ../../src/stx/common/trex_stack_linux_based.cpp:999:28: error: catching polymorphic type 'class TrexException' by value [-Werror=catch-value=]
|   999 |     } catch (TrexException e) {
|       |                            ^
| ../../src/stx/common/trex_stack_linux_based.cpp: In constructor 'CSharedNSIfNode::CSharedNSIfNode(const string&, const string&, const string&, const string&, const stri
ng&, CMcastFilter&, bool)':
| ../../src/stx/common/trex_stack_linux_based.cpp:1043:28: error: catching polymorphic type 'class TrexException' by value [-Werror=catch-value=]
|  1043 |     } catch (TrexException e) {
|       |                            ^
| ../../src/stx/common/trex_stack_linux_based.cpp: In function 'bool run_in_ns(const string&, const string&, const string&, bool, std::string&)':
| ../../src/stx/common/trex_stack_linux_based.cpp:1128:29: error: catching polymorphic type 'class TrexException' by value [-Werror=catch-value=]
|  1128 |     } catch ( TrexException e ) {
|       |                             ^
| cc1plus: all warnings being treated as errors
|
| Build failed
|  -> task in 'bp-sim-64-debug' failed with exit status 1 (run with -v to display more information)

Signed-off-by: Emmanuel Roullit <emmanuel.roullit@gmail.com>