add missing <ctime> include
This fixes the following warning in trex_owner.cpp:
  error: ‘time’ was not declared in this scope
  static unsigned int next_seed = time(nullptr);

Signed-off-by: Gabriel Ganne <gabriel.ganne@gmail.com>